# Generated by Django 2.0.13 on 2020-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amounted_mentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordId', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=10)),
                ('hits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assoicated_words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordId', models.CharField(max_length=30)),
                ('word', models.CharField(max_length=30)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='News_infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordId', models.CharField(max_length=200)),
                ('news_id', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40)),
                ('provider_link_page', models.CharField(max_length=300, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Identifier', models.CharField(max_length=100)),
                ('wordId', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('meaning', models.TextField()),
            ],
        ),
    ]
